from typing import Protocol


class StateStore(Protocol):
    def is_duplicate(self, digest_date: str, content_hash: str) -> bool: ...
    def save_draft(self, digest_date: str, content_hash: str, draft_media_id: str) -> None: ...
    def mark_published(self, draft_media_id: str, publish_id: str, publish_status: str) -> None: ...
